name: lnq
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0+1
  flutter_riverpod: ^2.4.1
  supabase_flutter: ^1.10.19
  routemaster: ^1.0.1
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.0
  fpdart: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7
  uuid: ^4.1.0
  intl: ^0.18.1
  phosphor_flutter: ^2.0.0
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  pinput: ^3.0.1
  file_picker: ^5.5.0
  dropdown_button2: ^2.3.9
  skeletonizer: ^0.8.0
  easy_debounce: ^2.0.3
  flextras: ^1.0.0
  encrypt: ^5.0.3
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.0
  xtended: ^0.1.5
  flutter_appauth: ^6.0.2
  envied_flutter: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  envied_flutter_generator: ^0.3.0


flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: fonts/ClashDisplay-Bold.otf
          weight: 700
        - asset: fonts/ClashDisplay-SemiBold.otf
          weight: 600
        - asset: fonts/ClashDisplay-Medium.otf
          weight: 500
        - asset: fonts/ClashDisplay-Regular.otf
          weight: 400
        - asset: fonts/ClashDisplay-Light.otf
          weight: 300
        - asset: fonts/ClashDisplay-ExtraLight.otf
          weight: 200


    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200

    - family: UnicaOne
      fonts:
        - asset: fonts/UnicaOne-Regular.ttf
          weight: 400